### ISSUE TITLE
These dictionary items do not have defaults

### ISSUE THREAD

**Issue by nellyt** [gjr80/weewx-polarwindplot#31]
https://github.com/gjr80/weewx-polarwindplot/blob/42a870cd09005ab789a76b952ba222a8ed122741/skins/PolarWindPlotTestSkin/skin.conf#L47
```
    image_width = 382
    image_height = 361
    image_background_circle_color = 0xF5F5F5
    image_background_box_color = 0xF5C696
    image_background_range_ring_color = 0xC3D9DD
    image_background_image = none
    font_path = /usr/share/fonts/truetype/freefont/FreeSansBold.ttf
    plot_font_size  = 10
    plot_font_color = 0x000000
    plot_border = 5
    legend_bar_width = 10
    legend_font_size = 10
    legend_font_color = 0x000000
    label_font_size = 12
    label_font_color = 0x000000
```
My attempt at a minimal skin.conf for testing shows that the above items (possibly) should have defaults

**Comment by gjr80** [comment]
Done with following exceptions/notes:

- at the moment `image_width` and `image_height` still default to `None` (though the distribution skin will have values). This will cause the generator to fail if `image_width` and `image_height` values are not specified for some reason. The values that exist at present (382 and 361) only came about because that was the size that fitted the space on my Saratoga template page. Looking at the weeWX plot engine for graphs it does use defaults, guess we should follow that behaviour. Maybe some round numbers like 400 wide and 380 high?

- `font_path` defaults to `None` which will cause the generator to fail (distribution skin will have a `font_path` entry - have used a font from same family as the weeWX ImageGenerator so think we are safe in that regard. The default to `None` is the same behaviour as the weeWX plot engine.
