### ISSUE TITLE
Setting legend=False in rose/trail/spiral throws error

### ISSUE THREAD

**Issue by nellyt** [gjr80/weewx-polarwindplot#42]
Suspect solution will be in line 562 ish...

Something like -

```
def render_legend(self):
        """Render a polar plot legend."""
                if self.legend = False
                     return
```

- [ ] Test generation in test skin.config is currently commented out...uncomment it!

**Comment by gjr80** [comment]
== to check for equality but the pythonic way is

if not self.legend:

**Comment by gjr80** [comment]
Probably a lot of refactoring since this issue was raised but setting `legend = False` now renders a plot without the legend.
As an aside, other than the scatter plot the default is to display a legend with the user having the ability to hide the legend via the `legend` config option. For the scatter plot the legend is hidden with no option to make it visible.

**Comment by gjr80** [comment]
refer commit 5395dbbda0ef3c63af002032e90ca6e7b9c02cd3
